[package]

name = "termbox-sys"
version = "0.1.0"
authors = [
    "Greg Chapple <gregchapple1@gmail.com>",
    "Tom Jakubowski <tom@crystae.net>"
]

links = "termbox"
build = "build.rs"

[lib]
name = "termbox-sys"
path = "lib.rs"
